// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4axvrWH4QYxj3nWg21bRMcAH-8TCCII',
    appId: '1:495400717133:web:9393a1d33971f10ea4c504',
    messagingSenderId: '495400717133',
    projectId: 'studentdirectoryapp-22d4c',
    authDomain: 'studentdirectoryapp-22d4c.firebaseapp.com',
    storageBucket: 'studentdirectoryapp-22d4c.firebasestorage.app',
    measurementId: 'G-R54C4LV5VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArJfYLa6uEq2BelC_HLdf-Ajo-9d8IPU',
    appId: '1:495400717133:android:e20cf7b3b58908ffa4c504',
    messagingSenderId: '495400717133',
    projectId: 'studentdirectoryapp-22d4c',
    storageBucket: 'studentdirectoryapp-22d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-F4oyON-Hk1wwpmL0sAkW7ckZPo4FOKE',
    appId: '1:495400717133:ios:64a95488d19f9fb2a4c504',
    messagingSenderId: '495400717133',
    projectId: 'studentdirectoryapp-22d4c',
    storageBucket: 'studentdirectoryapp-22d4c.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-F4oyON-Hk1wwpmL0sAkW7ckZPo4FOKE',
    appId: '1:495400717133:ios:64a95488d19f9fb2a4c504',
    messagingSenderId: '495400717133',
    projectId: 'studentdirectoryapp-22d4c',
    storageBucket: 'studentdirectoryapp-22d4c.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl4axvrWH4QYxj3nWg21bRMcAH-8TCCII',
    appId: '1:495400717133:web:3561191e45c41aeca4c504',
    messagingSenderId: '495400717133',
    projectId: 'studentdirectoryapp-22d4c',
    authDomain: 'studentdirectoryapp-22d4c.firebaseapp.com',
    storageBucket: 'studentdirectoryapp-22d4c.firebasestorage.app',
    measurementId: 'G-J20TYVBHW2',
  );
}
